### ISSUE TITLE
Leaderboard for In the beginning was the deed

### ISSUE THREAD

**Issue by lordofthemark** [freezingsaddles/freezing-web#52] opened 2018-03-03 14:56 UTC
Ideally I would like people to get points equal to the number of times they have ridden the segment that they have ridden the fewest times (IE if there were three segments, A, B, and C, and someone has ridden A and B 5 times, but ridden C 2 times, there score would be 2) 

Here is the complete list of segments for this prize.  

The Deed 7 (WB on Washington Blvd)
N. Arlington to N. Illinois
New Bike Lane on Wilson Blvd.
BikeArlington Commuter Counter (New,   downhill)
Library Sprint - if you're lucky
The Deed 8 (NB Eads)
The Deed 9 (NB Eads)
The Deed 10 (Hayes NB)
The Deed 11 (Hayes SB)
The Deed 12(18th EB)
The Deed 13(18th WB)
The Deed 14(Crystal NB)
The Deed 15(Crystal SB)
The Deed
The Deed 4 (King Street Buffered SB)
 The Deed 2
The Deed 5 (SB Bolshevik Lane)
 The Deed 6 Prince Street
Cam'ron Dash
The Deed 3
 King to Ft Ward Hillcrest
The Deed 18 (G Street)
The Deed 19 (Eye Street)
The Deed 16 (L Street)
 The Deed 17 (M Street)

Thanks for your assistance 
Ken

**Comment by hozn** [comment] 2018-03-03 23:41
Hi Ken, sorry to be a bit of a pain, but we need the actual numeric segment IDs.

**Comment by hozn** [comment] 2018-04-09 01:36
Updating for my own reference:
```sql
select athlete_id, athlete_name, min(segments_ridden_count) as least_ridden_segment_count from (select segment_id, count(e.id) as segments_ridden_count,
athlete_id,
a.display_name as athlete_name
from 
ride_efforts e
join rides r on r.id = e.ride_id 
join athletes a on a.id = r.athlete_id
where segment_id in (16702081, 1628209, 9916774, 14128360, 7311611, 16727683, 16727753, 16727959, 16728179, 16728938, 16729080, 16729134, 16700352, 16700518, 16700365, 16700527, 16700619, 2489428, 16700441, 7107707, 16946024, 16946140, 16945729, 16945780)
group by athlete_id, segment_id) as x  group by x.athlete_id, x.athlete_name order by least_ridden_segment_count desc
```

(Using some sloppy SQL that MySQL allows with ordering by the aggregate.)

**Comment by obscurerichard** [comment] 2019-01-03 22:03
For 2019:

lordofthemark's  
Default Ride Alexandria Infrastructure Pointless Prize, 2019
As discussed earlier I would like to re do last year's In the Beginning was the deed prize, but this time only infra in the City of Alexandria.

The goal here is to ride each of the included segments as many times as possible. The number of times yu ride your LEAST ridden segment is your "n" and the person with the highest n wins the prize.

Here is the list of segments

The location is followed by the name of the Strava segment.

King Street TCW to Janneys- NB The Deed

King Street TCW to Janneys - SB The Deed 4 (King Street Buffered SB)

King Street Janneys to Cedar- NB The Deed 2


King Street Janneys to Cedar - SB The Deed 5 (SB Bolshevik Lane)

Prince The Deed 6 Prince Street

Cameron Columbus to Buchanon Cam'ron Dash

Van Dorn - EB. The Deed 3

Van Dorn King to Ft Ward King to Ft Ward Hillcrest

For whomever is coding it this year,

Here are the strava segment numbers for the above

16700352
16700518
16700365
16700527
16700619
2489428
16700441
7107707


Hozn coded this last year, so the same code but with fewer segment codes should work.

**Comment by merlinorg** [comment] 2020-01-01 13:59
Duplicate of #127 in a reverse reality.

**Closed by merlinorg** 2020-01-01 13:59 UTC
Labels: duplicate, enhancement, good first issue, help wanted
