### ISSUE TITLE
Replace Weather Underground

### ISSUE THREAD

**Issue by peterwcode** [freezingsaddles/freezing-web#116] opened 2019-03-01 06:39 UTC
The free API is dead and needs to be replaced: https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api

**Comment by peterwcode** [comment] 2019-03-01 07:06
Has anyone looked at the National Weather Service APIs? https://www.weather.gov/documentation/services-web-api#/

To get historical data it looks like you start with a lat long point:
https://api.weather.gov/points/38.5,-77.5

Look for properties.observationStations and call that URL to get individual station identifiers, e.g. 
https://api.weather.gov/gridpoints/LWX/82,50/stations
shows Stafford Regional Airport as "KRMN".

Then comes the huge call, getting all historical observations. (While it is possible to request a single observation with a URL like https://api.weather.gov/stations/KRMN/observations/2019-03-01T06:35:00+00:00, you have to know the exact time; pick an arbitrary time and you get a 404.)

https://api.weather.gov/stations/KRMN/observations

properties.presentWeather tells you if it's raining or snowing and of course there are properties for things like temperature and wind speed.

**Comment by hozn** [comment] 2019-03-01 10:57
I originally used the national weather service API; the data was just really poor quality (mostly empty values), but maybe I didn't discover the secret high quality stations to use. Also, that was a long time ago so hopefully both the API and the data is better now.

**Comment by peterwcode** [comment] 2019-03-01 13:00
Also it's unfortunate that NWS is US-only; I assume WU handled global locations.

It looks like the NWS data goes back about 1.5 years; it might be interesting to compare their data for BAFS 2018 with what was fetched from WU. 

I think this was mentioned on WABF discussion about limiting API calls: for weather, bafs could round lat/long, effectively snapping all points to a grid. (bafs does still only look up the conditions at the starting point of a ride, right?) So maybe export from bafs 2018 data the rounded lat/long (which would also help preserve rider privacy) + ride start time + weather conditions, then write some code to get the corresponding NWS data?  To me it looks like rounding to the nearest 0.1 degree would be pretty good for this purpose. For WU I would have argued for 0.01 degree because there are so many Personal Weather Stations that that might help, but since NWS has so few stations 0.1 would be better.

**Comment by obscurerichard** [comment] 2019-03-04 14:51
This is a known issue, this is a duplicate of https://github.com/freezingsaddles/freezing-sync/issues/5 (the syncing happens in the `freezing-sync` component). Alas we haven't had time to fix it yet. The leading candidate is the Dark Sky API: https://darksky.net/dev

**Closed by obscurerichard** 2019-03-04 14:51 UTC
Labels: duplicate

**Comment by obscurerichard** [comment] 2019-03-04 14:53
@peterwcode I would welcome help in fixing this, please collaborate with me on https://github.com/freezingsaddles/freezing-sync/issues/5
